# Generated by Django 3.2.9 on 2021-12-03 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('provider', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('preventive_maintenance', 'Manutenção preventiva'), ('corrective_maintenance', 'Manutenção corretiva'), ('manufacture', 'Fabricação'), ('periodic_actions', 'Ações periódicas')], max_length=50)),
                ('downtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.machine')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.occurrence')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.occurrence')),
            ],
        ),
    ]
