# Generated by Django 3.2.9 on 2021-12-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencematerial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.material'),
        ),
    ]
