# Generated by Django 3.2.9 on 2021-12-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0002_alter_occurrencematerial_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='material_cost',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='occurrenceservice',
            name='cost',
        ),
    ]
