# Generated by Django 3.2.9 on 2021-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('eletric', 'Eletric'), ('hidraulic', 'Hidraulic'), ('mechanic', 'Mechanic'), ('eletronic', 'Eletronic'), ('pneumatic', 'Pneumatic'), ('consumable', 'Consumable')], max_length=10),
        ),
    ]
