# Generated by Django 3.2.9 on 2021-12-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
    ]
