# Generated by Django 3.2.9 on 2021-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('eletric', 'Elétrico'), ('hidraulic', 'Hidráulico'), ('mechanic', 'Mecânico'), ('eletronic', 'Eletrônico'), ('pneumatic', 'Pneumático'), ('consumable', 'Consumível')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
